Logika/src/logika/backing/HistoriaDeUsuarioBean.java
package logika.backing;

import java.io.Serializable;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;

import logika.dao.DAOHistoriaDeUsuario;
import logika.dao.DAOProyecto;
import logika.model.HistoriaDeUsuario;
import logika.model.Proyecto;


@Named
@RequestScoped
public class HistoriaDeUsuarioBean implements Serializable {
	private static final long serialVersionUID = 7156139487103883898L;
	private ArrayList<HistoriaDeUsuario> historiaDeUsuario = new ArrayList<HistoriaDeUsuario>();
	HistoriaDeUsuario seleccionado;
	HistoriaDeUsuario nuevo;
	FacesMessage fmessage;
	FacesContext fcontext = FacesContext.getCurrentInstance();

	public HistoriaDeUsuarioBean() {
		seleccionado = new HistoriaDeUsuario();
		nuevo = new HistoriaDeUsuario();
	}

	public void guardar() {
		System.out.println("4");
		DAOHistoriaDeUsuario dao = new DAOHistoriaDeUsuario();	
		try {
			System.out.println("5");
			dao.guardar(nuevo);
			seleccionado = new HistoriaDeUsuario();
			nuevo = new HistoriaDeUsuario();
		} catch (Exception e) {
			fmessage = new FacesMessage(FacesMessage.SEVERITY_ERROR, e.toString(), e.toString());
			fcontext.addMessage(null, fmessage);
			e.printStackTrace();
		}
	}

	public ArrayList<HistoriaDeUsuario> getHistoriaDeUsuario() {
		DAOHistoriaDeUsuario dao = new DAOHistoriaDeUsuario();
		try {
			historiaDeUsuario = dao.getHistoriaDeUsuario();
			System.out.println("historiaDeUsuario " + historiaDeUsuario);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return historiaDeUsuario;
	}
	
	public ArrayList<String> getNombreSprint() {
		DAOHistoriaDeUsuario dao = new DAOHistoriaDeUsuario();
		ArrayList<String> sprintlist = new ArrayList<String>();
		try {
			sprintlist=dao.getNombreSprint(); 
			System.out.println("getNombreSprint " + sprintlist);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return sprintlist;
	}
	
	public ArrayList<String> getNombreProyecto() {
		DAOHistoriaDeUsuario dao = new DAOHistoriaDeUsuario();
		ArrayList<String> sprintlist = new ArrayList<String>();
		try {
			sprintlist=dao.getNombreProyecto(); 
			System.out.println("getNombreProyecto " + sprintlist);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return sprintlist;
	}
	
	public ArrayList<String> getResponsable() {
		DAOHistoriaDeUsuario dao = new DAOHistoriaDeUsuario();
		ArrayList<String> sprintlist = new ArrayList<String>();
		try {
			sprintlist=dao.getResponsable(); 
			System.out.println("getResponsable " + sprintlist);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return sprintlist;
	}

	public ArrayList<String> getRol() {
		DAOHistoriaDeUsuario dao = new DAOHistoriaDeUsuario();
		ArrayList<String> sprintlist = new ArrayList<String>();
		try {
			sprintlist=dao.getRol(); 
			System.out.println("getRol " + sprintlist);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return sprintlist;
	}
	
	public void mostrarSeleccionado() {
		nuevo = seleccionado;
	}

	public void setHistoriaDeUsuario(ArrayList<HistoriaDeUsuario> historiaDeUsuario) {
		this.historiaDeUsuario = historiaDeUsuario;
	}

	public HistoriaDeUsuario getSeleccionado() {
		return seleccionado;
	}

	public void setSeleccionado(HistoriaDeUsuario seleccionado) {		
		this.seleccionado = seleccionado;
	}

	public HistoriaDeUsuario getNuevo() {
		return nuevo;
	}

	public void setNuevo(HistoriaDeUsuario nuevo) {
		this.nuevo = nuevo;
	}

	
}

Logika/src/logika/backing/HomeBean.java
package logika.backing;

import java.io.Serializable;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;

import org.primefaces.model.chart.Axis;
import org.primefaces.model.chart.AxisType;
import org.primefaces.model.chart.CategoryAxis;
import org.primefaces.model.chart.LineChartModel;
import org.primefaces.model.chart.LineChartSeries;
import org.primefaces.model.chart.PieChartModel;

import com.oracle.jrockit.jfr.Producer;

import logika.dao.DAOUsuario;
import logika.model.Usuario;

@Named
@RequestScoped
public class HomeBean implements Serializable {
	private static final long serialVersionUID = -8030839164392647335L;
	FacesMessage fmessage;
	FacesContext fcontext = FacesContext.getCurrentInstance();
	private LineChartModel sprintBackChart;
	private LineChartModel prodBackChart;
	private PieChartModel pieModel1= new PieChartModel();
	
	public HomeBean() {
		loadCharts();
	}

	private void loadCharts() {
		loadProdBackChart();
		createPieModel1();
	}

	private void loadProdBackChart() {
		LineChartSeries creados = new LineChartSeries(), terminados = new LineChartSeries();
		Axis xAxis = new CategoryAxis("Months");
		Axis yAxis;
		prodBackChart = new LineChartModel();

		yAxis = prodBackChart.getAxis(AxisType.Y);
		xAxis.setLabel("Meses");
        yAxis.setMin(0);
        yAxis.setMax(10);

		prodBackChart.getAxes().put(AxisType.X, xAxis);
		
		creados = generarCantTotal();
		terminados = generarCantTerminados();
		creados.setLabel("Creados");
		terminados.setLabel("Terminados");		
		prodBackChart.addSeries(creados);
		prodBackChart.addSeries(terminados);
		
		prodBackChart.setTitle("DashBoard Product Backlog");
		prodBackChart.setLegendPosition("e");
	}
	
    private void createPieModel1() {
        pieModel1 = new PieChartModel();
 
        pieModel1.set("Por Hacer", 540);
        pieModel1.set("Haciendo", 325);
        pieModel1.set("Terminado", 702);
        pieModel1.setTitle("Sprint Backlog");
        pieModel1.setLegendPosition("w");
        pieModel1.setShadow(false);
    }

	private LineChartSeries generarCantTerminados() {
		LineChartSeries series1 = new LineChartSeries();
		series1.set(1, 2);
        series1.set(2, 1);
        series1.set(3, 3);
        series1.set(4, 6);
        series1.set(5, 8);
		return series1;
	}

	private LineChartSeries generarCantTotal() {
		LineChartSeries series2 = new LineChartSeries();
        series2.set(1, 6);
        series2.set(2, 3);
        series2.set(3, 2);
        series2.set(4, 7);
        series2.set(5, 9);
		return series2;
	}

	private void loadSprintBackChart() {
		LineChartSeries creados = new LineChartSeries(), terminados = new LineChartSeries();
		prodBackChart = new LineChartModel();
		creados.setLabel("Creados");
		terminados.setLabel("terminados");
		sprintBackChart.getAxes().put(AxisType.X, new CategoryAxis("Months"));
		//creados = generarTotal();
		//terminados = generarTotalTerminados();
	
		sprintBackChart.addSeries(creados);
		sprintBackChart.addSeries(terminados);
	}

	public LineChartModel getSprintBackChart() {
		return sprintBackChart;
	}

	public void setSprintBackChart(LineChartModel sprintBackChart) {
		this.sprintBackChart = sprintBackChart;
	}

	public LineChartModel getProdBackChart() {
		return prodBackChart;
	}

	public void setProdBackChart(LineChartModel prodBackChart) {
		this.prodBackChart = prodBackChart;
	}
	
	public PieChartModel getPieModel1() {
		return pieModel1;
	}

	public void setPieModel1(PieChartModel pieModel1) {
		this.pieModel1 = pieModel1;
	}

}

Logika/WebContent/HistoriasList.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	>
	<h:head>
        <title>Historia de usuario</title>
    </h:head>
<h:body>
	<ui:composition  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
		template="./WEB-INF/layout/template.xhtml">
		<ui:define name="top">
			<ul>
				<li><a class="icono" href="home.xhtml" style="font-family: Cooper, Comic Sans MS;font-style: italic;font-size: 2em;">LOGIkA</a></li>
				<li><a href="UsuariosList.xhtml">Usuarios</a></li>
				<li><a href="RolesList.xhtml">Roles</a></li>
				<li><a href="ProyectosList.xhtml">Proyectos</a></li>
				<li><a href="SprintList.xhtml">Sprints</a></li>
				<li><a href="HistoriasList.xhtml">Historias de usuarios</a></li>
			</ul>
		</ui:define>
		<ui:define name="content">
			<h:form id="form">
            	<p:growl id="messages" showDetail="true" />
	            <p:panel header="Historia de Usuario" id="historiaInfo" >
    	        	<p:panelGrid columns="2">
    	        		<!-- <label>Id historia: </label>
            			<p:inputText value="#{historiaDeUsuarioBean.nuevo.idHistoria}"/>  -->
        	    		<label>Resumen: </label>
            			<p:inputText value="#{historiaDeUsuarioBean.nuevo.resumen}"/>
            			<label>Descripcion: </label>
            			<p:inputText value="#{historiaDeUsuarioBean.nuevo.descripcion}"/>
            			<label>Prioridad: </label>
            			<p:inputText id="button" value="#{historiaDeUsuarioBean.nuevo.prioridad}" showOn="button"/>
            			<label>Estado: </label>
            			<p:inputText id="button1" value="#{historiaDeUsuarioBean.nuevo.estadoKamban}" showOn="button"/>
            			
            			<p:outputLabel for="Sprint" value="Sprint:" />
        				<p:selectOneMenu id="Sprint" value="#{historiaDeUsuarioBean.nuevo.nombreSprint}" dynamic="true" style="width:125px">
           				 <f:selectItem itemLabel="" itemValue="" />           				 
           				 <f:selectItems value="#{historiaDeUsuarioBean.nombreSprint}" />
        				</p:selectOneMenu>
        				
            			<p:outputLabel for="proyecto" value="Nombre proyecto:" />
        				<p:selectOneMenu id="proyecto" value="#{historiaDeUsuarioBean.nuevo.idProyecto}" dynamic="true" style="width:125px">
           				 <f:selectItem itemLabel="" itemValue="" />
           				 <f:selectItems value="#{historiaDeUsuarioBean.nombreProyecto}" />
        				</p:selectOneMenu>
       					
        				
            			<p:outputLabel for="responsable" value="Responsable:" />
        				<p:selectOneMenu id="responsable" value="#{historiaDeUsuarioBean.nuevo.nombreUsuario}" dynamic="true" style="width:125px">
           				 <f:selectItem itemLabel="" itemValue="" />
           				 <f:selectItems value="#{historiaDeUsuarioBean.responsable}" />
        				</p:selectOneMenu>
        				
        				<p:outputLabel for="rol" value="Rol:" />
        				<p:selectOneMenu id="rol" value="#{historiaDeUsuarioBean.nuevo.rol}" dynamic="true" style="width:125px">
           				 <f:selectItem itemLabel="" itemValue="" />
           				 <f:selectItems value="#{historiaDeUsuarioBean.rol}" />
        				</p:selectOneMenu>
            			
    	        	</p:panelGrid>            	
        	    	<p:commandButton value="Guardar" icon="ui-icon-dis" actionListener="#{historiaDeUsuarioBean.guardar}" 
            		update=":form:historiasList, :form:historiaInfo"></p:commandButton>
            	</p:panel>
	            <p:dataTable id="historiasList" value="#{historiaDeUsuarioBean.historiaDeUsuario}" var="historiasList" selection="#{historiaDeUsuarioBean.seleccionado}" 
    	        selectionMode="single" rowKey="#{historiasList.resumen}">
        	    	<p:ajax event="rowSelect" update=":form:historiaInfo" listener="#{historiaDeUsuarioBean.mostrarSeleccionado}"></p:ajax>
            	    <f:facet name="header">Historia de usuario</f:facet>
            	    <p:column headerText="idHistoria">
                    	#{historiasList.idHistoria}
	                </p:column>
                	<p:column headerText="resumen">
                    	#{historiasList.resumen}
	                </p:column>
    	            <p:column headerText="Descripcion">
						#{historiasList.descripcion}
            	    </p:column>
                	<p:column headerText="prioridad">
						#{historiasList.prioridad}
	                </p:column>
	                <p:column headerText="estadoKamban">
						#{historiasList.estadoKamban}
	                </p:column>
	                <p:column headerText="idSprint">
						#{historiasList.idSprint}
	                </p:column>
	                <p:column headerText="idProyecto">
						#{historiasList.idProyecto}
	                </p:column>
	                <p:column headerText="nombreUsuario">
						#{historiasList.nombreUsuario}
	                </p:column>
    	        </p:dataTable>
    	    </h:form>
		</ui:define>
		
	</ui:composition>
</h:body>
</html>

Logika/WebContent/ProyectosList.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	>
	<h:head>
        <title>Proyectos</title>
    </h:head>
<h:body>
	<ui:composition  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
		template="./WEB-INF/layout/template.xhtml">
		<ui:define name="top">
			<ul>
				<li><a class="icono" href="home.xhtml" style="font-family: Cooper, Comic Sans MS;font-style: italic;font-size: 2em;">LOGIkA</a></li>
				<li><a href="UsuariosList.xhtml">Usuarios</a></li>
				<li><a href="RolesList.xhtml">Roles</a></li>
				<li><a href="ProyectosList.xhtml">Proyectos</a></li>
				<li><a href="SprintList.xhtml">Sprints</a></li>
				<li><a href="HistoriasList.xhtml">Historias de usuarios</a></li>
			</ul>
		</ui:define>
		<ui:define name="content">
			<h:form id="form">
            	<p:growl id="messages" showDetail="true" />
	            <p:panel header="Información Proyecto" id="proyectoInfo" >
    	        	<p:panelGrid columns="2">
    	        		<p:outputLabel for="id_proyecto" value="Id_proyecto: "/>
            			<p:inputText id="id_proyecto" value="#{proyectoBean.nuevo.idProyecto}" required="true"/>
            			<p:outputLabel for="nombre" value="Nombre: "/>
            			<p:inputText id="nombre" value="#{proyectoBean.nuevo.nombre}" required="true"/>
            			<p:outputLabel for="descripcion" value="Descripcion: "/>
            			<p:inputText id="descripcion" value="#{proyectoBean.nuevo.descripcion}"  required="true"/>
            			<p:outputLabel for="button" value="Fecha inicio: "/>
            			<p:calendar id="button" value="#{proyectoBean.nuevo.fechaInicio}" showOn="button"  pattern="dd/MM/yyyy" datePattern="dd/MM/yyyy"  required="true"/>
            			<p:outputLabel for="button1" value="Fecha fin: "/>
            			<p:calendar id="button1" value="#{proyectoBean.nuevo.fechaFin}" showOn="button" pattern="dd/MM/yyyy" datePattern="dd/MM/yyyy"  required="true"/>
            			
      				 	<p:outputLabel for="lazy" value="Estado:" />
        			<p:selectOneMenu id="lazy" value="#{proyectoBean.nuevo.estado}" dynamic="true" style="width:125px">
            			<f:selectItem itemLabel=" " itemValue="" />
           				 <f:selectItems value="#{proyectoBean.listadoEstado()}" required="true" />
       				 </p:selectOneMenu>

    	        	</p:panelGrid>            	
        	    	<p:commandButton value="Guardar" icon="ui-icon-dis" actionListener="#{proyectoBean.guardar}" 
            		update=":form:proyectosList, :form:proyectoInfo :form:messages"></p:commandButton>
            	</p:panel>
	            <p:dataTable id="proyectosList" value="#{proyectoBean.proyecto}" var="proyectosList" selection="#{proyectoBean.seleccionado}" 
    	        selectionMode="single" rowKey="#{proyectosList.nombre}">
        	    	<p:ajax event="rowSelect" update=":form:proyectoInfo" listener="#{proyectoBean.mostrarSeleccionado}"></p:ajax>
            	    <f:facet name="header">Lista de Proyectos</f:facet>
            	    <p:column headerText="Id_proyecto">
                    	#{proyectosList.idProyecto}
	                </p:column>
                	<p:column headerText="Nombre">
                    	#{proyectosList.nombre}
	                </p:column>
    	            <p:column headerText="Descripcion">
						#{proyectosList.descripcion}
            	    </p:column>
                	<p:column headerText="Fecha_inicio">
						#{proyectosList.fechaInicio}
	                </p:column>
	                <p:column headerText="Fecha_fin">
						#{proyectosList.fechaFin}
	                </p:column>
	                <p:column headerText="Estado">
						#{proyectosList.estado}
	                </p:column>
    	        </p:dataTable>
    	    </h:form>
		</ui:define>
		
	</ui:composition>
</h:body>
</html>

Logika/WebContent/RolesList.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core" 
	xmlns:p="http://primefaces.org/ui">
	<h:head>
        <title>Roles</title>
    </h:head>
<h:body>
	<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
		template="./WEB-INF/layout/template.xhtml">
		<ui:define name="top">
			<ul>
				<li><a class="icono" href="home.xhtml" style="font-family: Cooper, Comic Sans MS;font-style: italic;font-size: 2em;">LOGIkA</a></li>
				<li><a href="UsuariosList.xhtml">Usuarios</a></li>
				<li><a href="RolesList.xhtml">Roles</a></li>
				<li><a href="ProyectosList.xhtml">Proyectos</a></li>
				<li><a href="SprintList.xhtml">Sprints</a></li>
				<li><a href="HistoriasList.xhtml">Historias de usuarios</a></li>
			</ul>
		</ui:define>
		<ui:define name="content">
        	<h:form id="form">
            	<p:growl id="messages"/>
	            <p:panel header="Informacion Roles" id="rolInfo" >
    	        	<p:panelGrid columns="2">
        	    		<label>Descripcion: </label>
            			<p:inputText value="#{rolBean.nuevo.descripcion}"/>
            			<label>Permiso: </label>
        				<p:selectOneRadio id="permiso" value="#{rolBean.nuevo.permiso.id}" unselectable="true">
            				<f:selectItems value="#{rolBean.permisos}" var="c" itemLabel="#{c.descripcion}" itemValue="#{c.id}"/>
        				</p:selectOneRadio>
    	        	</p:panelGrid>
        	    	<p:commandButton value="Guardar" icon="ui-icon-dis" actionListener="#{rolBean.guardar}" disabled="#{sesion.permiso.descripcion.equals('SOLO VISUALIZACIÓN')}"
            		update=":form:rolesList, :form:rolInfo"></p:commandButton>
            	</p:panel>
	            <p:dataTable id="rolesList" value="#{rolBean.roles}" var="rolList" selection="#{rolBean.seleccionado}" 
    	        selectionMode="single" rowKey="#{rolList.codigo}">
        	    	<p:ajax event="rowSelect" update=":form:rolInfo" listener="#{rolBean.mostrarSeleccionado}"></p:ajax>
            	    <f:facet name="header">Lista de roles</f:facet>
            	    <p:column headerText="Codigo" style="width=20%">
                    	#{rolList.codigo}
	                </p:column>
                	<p:column headerText="Nombre" style="width=80%">
                    	#{rolList.descripcion}
	                </p:column>
			     	<p:column headerText="Permiso" style="width=80%">
                    	#{rolList.permiso.descripcion}
	                </p:column>
    	        </p:dataTable>
    	    </h:form>
		</ui:define>
	</ui:composition>
</h:body>
</html>

Logika/WebContent/SprintList.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">
	<h:head>
        <title>Sprint</title>
    </h:head>
<h:body>
	<ui:composition  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
		template="./WEB-INF/layout/template.xhtml">
		<ui:define name="top">
			<ul>
				<li><a class="icono" href="home.xhtml" style="font-family: Cooper, Comic Sans MS;font-style: italic;font-size: 2em;">LOGIkA</a></li>
				<li><a href="UsuariosList.xhtml">Usuarios</a></li>
				<li><a href="RolesList.xhtml">Roles</a></li>
				<li><a href="ProyectosList.xhtml">Proyectos</a></li>
				<li><a href="SprintList.xhtml">Sprints</a></li>
				<li><a href="HistoriasList.xhtml">Historias de usuarios</a></li>
			</ul>
		</ui:define>
		<ui:define name="content">
			<h:form id="form">
            	<p:growl id="messages" showDetail="true" />
	            <p:panel header="Informacion Sprint" id="sprintInfo" >
    	        	<p:panelGrid columns="2">
        	    		<p:outputLabel value="Nombre:" for="nombre"/>
            			<p:inputText id="nombre" value="#{sprintBean.nuevo.nombre}" required="true"/>
            			<p:outputLabel for="fechaIni" value="Fecha inicio:" />
            			<p:calendar id="fechaIni" value="#{sprintBean.nuevo.fechaInicio}" showOn="button"  pattern="dd/MM/yyyy" datePattern="dd/MM/yyyy"  required="true"/>
            			<p:outputLabel for="fechaFin" value="Fecha fin:" />
            			<p:calendar id="fechaFin" value="#{sprintBean.nuevo.fechaFin}" showOn="button" pattern="dd/MM/yyyy" datePattern="dd/MM/yyyy"  required="true"/>
            			<p:outputLabel for="fechaFinEst" value="Fecha fin Estimada:" />
            			<p:calendar id="fechaFinEst" value="#{sprintBean.nuevo.fechaFinEstimada}" showOn="button" pattern="dd/MM/yyyy" datePattern="dd/MM/yyyy"  required="true"/>
            			<p:outputLabel for="proyecto" value="Proyecto Asignado:"/>
            			<p:autoComplete id="proyecto" value="#{sprintBean.nuevo.descProyecto}" completeMethod="#{sprintBean.completeProyecto}"
                        forceSelection="true" />
    	        	</p:panelGrid>            	
        	    	<p:commandButton value="Guardar" icon="ui-icon-dis" actionListener="#{sprintBean.guardar}" disabled="#{sesion.permiso.descripcion.equals('SOLO VISUALIZACIÓN')}"
            		update=":form:sprintList, :form:sprintInfo"></p:commandButton>
            	</p:panel>
	            <p:dataTable id="sprintList" value="#{sprintBean.sprints}" var="sprintList" selection="#{sprintBean.seleccionado}" 
    	        selectionMode="single" rowKey="#{sprintList.nombre}">
        	    	<p:ajax event="rowSelect" update=":form:sprintInfo" listener="#{sprintBean.mostrarSeleccionado}"></p:ajax>
            	    <f:facet name="header">Sprint Backlogs</f:facet>
                	<p:column headerText="Nombre">
                    	#{sprintList.nombre}
	                </p:column>
                	<p:column headerText="Fecha inicio">
						#{sprintList.fechaInicio}
	                </p:column>
	                <p:column headerText="Fecha fin">
						#{sprintList.fechaFin}
	                </p:column>
	                <p:column headerText="proyecto">
						#{sprintList.descProyecto}
	                </p:column>
    	        </p:dataTable>
    	    </h:form>
		</ui:define>
	</ui:composition>
</h:body>
</html>

Logika/WebContent/home.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<h:body>
	<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
		template="./WEB-INF/layout/template.xhtml">
		<ui:define name="top">
			<ul>
				<li><a class="icono" href="home.xhtml" style="font-family: Cooper, Comic Sans MS;font-style: italic;font-size: 2em;">LOGIkA</a></li>
				<li><a href="UsuariosList.xhtml">Usuarios</a></li>
				<li><a href="RolesList.xhtml">Roles</a></li>
				<li><a href="ProyectosList.xhtml">Proyectos</a></li>
				<li><a href="SprintList.xhtml">Sprints</a></li>
				<li><a href="HistoriasList.xhtml">Historias de usuarios</a></li>
			</ul>			
		</ui:define>
		<ui:define name="content">				
				<h:outputText class="titulo" value="Bienvenido #{sesion.nombre.concat(' ').concat(sesion.apellido)}"></h:outputText>
				<p:chart type="line" model="#{homeBean.prodBackChart}" style="height:300px;"/>				
				<br /><br />
				<br /><br />
				<p:chart type="pie" model="#{homeBean.pieModel1}" style="width:400px;height:300px" />
		</ui:define>
	</ui:composition>
</h:body>
</html>